/* dsh-file-mention — generated by scripts/build.mjs; edit src/, then run `npm run build`. */
window.__ModuleLoader__.load({
	id: "dsh-file-mention",
	factory: (require) => {
		var module = { exports: {} };
		var exports = module.exports;
		Object.defineProperty(exports, Symbol.toStringTag, { value: "Module" });
		// ---- src/core.js (inlined) ----
		/**
		 * dsh-file-mention —— 规则匹配核心（纯函数，零依赖，可独立测试）
		 *
		 * 实现 gitignore/.aiinclude 风格的路径匹配子集：
		 *   - `#` 注释、空行忽略
		 *   - `!` 前缀表示否定（最后匹配者生效）
		 *   - 末尾 `/` 表示仅目录
		 *   - 开头 `/` 表示锚定于基准目录
		 *   - 含 `/` 的模式按完整相对路径匹配；不含 `/` 的模式按 basename 任意层级匹配
		 *   - `*` 匹配段内任意字符、`?` 匹配单字符、`**` 跨段匹配
		 */
		
		/** 段 → 正则片段：支持 *（段内任意）、?（单字符），其余按字面量转义。 */
		function segmentToRegex(seg) {
		  let out = ''
		  for (const ch of seg) {
		    if (ch === '*') out += '[^/]*'
		    else if (ch === '?') out += '[^/]'
		    else out += ch.replace(/[.+^${}()|[\]\\]/g, '\\$&')
		  }
		  return out
		}
		
		/** 编译规则行集合为可复用的匹配规则数组。 */
		function compileRules(lines) {
		  const rules = []
		  for (let raw of lines) {
		    raw = raw.trim()
		    if (raw === '' || raw.startsWith('#')) continue
		    let negate = false
		    if (raw.startsWith('!')) {
		      negate = true
		      raw = raw.slice(1).trim()
		    }
		    if (raw === '') continue
		    const dirOnly = raw.endsWith('/')
		    if (dirOnly) raw = raw.slice(0, -1)
		    let anchored = raw.startsWith('/')
		    if (anchored) raw = raw.slice(1)
		    if (raw === '') continue
		    const hasSlash = raw.includes('/')
		    try {
		      const src = raw
		        .split('/')
		        .map((seg) => (seg === '**' ? '(?:.*)' : segmentToRegex(seg)))
		        .join('/')
		      rules.push({ negate, dirOnly, anchored, hasSlash, re: new RegExp('^' + src + '$') })
		    } catch {
		      // 非法模式跳过
		    }
		  }
		  return rules
		}
		
		/**
		 * 返回 rel 命中的最后一条规则（gitignore 语义：最后匹配者生效）；
		 * 未命中返回 undefined。
		 */
		function lastMatchRule(rules, rel, isDir) {
		  let win
		  for (const r of rules) {
		    if (r.dirOnly && !isDir) continue
		    if (r.anchored || r.hasSlash) {
		      if (r.re.test(rel)) win = r
		    } else {
		      const base = rel.slice(rel.lastIndexOf('/') + 1)
		      if (r.re.test(base) || r.re.test(rel)) win = r
		    }
		  }
		  return win
		}
		
		/** 判断相对路径 rel 是否命中规则集（最后匹配者生效，未命中为 false）。 */
		function matchRules(rules, rel, isDir) {
		  const win = lastMatchRule(rules, rel, isDir)
		  return win !== undefined ? !win.negate : false
		}
		
		/**
		 * 按查询词过滤文件列表：匹配 basename 或完整路径（大小写不敏感）。
		 * 客户端 @ 菜单的过滤逻辑，独立出来以便测试。
		 */
		function filterFiles(files, query, limit = 50) {
		  const q = String(query || '').trim().toLowerCase()
		  let matches = files
		  if (q !== '') {
		    matches = files.filter((f) => {
		      const base = f.slice(f.lastIndexOf('/') + 1).toLowerCase()
		      return base.includes(q) || f.toLowerCase().includes(q)
		    })
		  }
		  return matches.slice(0, limit)
		}
		
		// ---- src/client.js (inlined) ----
		/**
		 * dsh-file-mention —— Client 半体
		 *
		 * 注册 '@' 输入触发源（与技能 / 菜单、@pluginId、@子代理 同一套 inputTriggers 机制）：
		 *   - 输入 @ 弹出 file 分组，按文件名/路径实时过滤
		 *   - 选中后插入 `@相对路径 ` 到输入框，模型看到路径后直接读取文件
		 *   - 列表经 Host 的 /file-mention/list HTTP 路由获取，客户端 30 秒缓存
		 *
		 * 构建时由 scripts/build.mjs 将 src/core.js 内联，并包装为
		 * `window.__ModuleLoader__.load({ id, factory })` 经典脚本格式。
		 */
		
		const name = 'dsh-file-mention'
		const inject = ['inputTriggers']
		
		function apply(ctx) {
		  const fetches = new Map()
		  const TTL = 30000
		
		  const fetchFiles = (sessionId) => {
		    const existing = fetches.get(sessionId)
		    if (existing !== undefined && Date.now() - existing.at < TTL) return existing.promise
		    if (existing !== undefined) fetches.delete(sessionId)
		    const promise = fetch('/file-mention/list', {
		      method: 'POST',
		      headers: { 'content-type': 'application/json' },
		      body: JSON.stringify({ sessionId }),
		    })
		      .then((response) => {
		        if (!response.ok) throw new Error(`HTTP ${response.status}`)
		        return response.json()
		      })
		      .then((value) => {
		        return value !== null && typeof value === 'object' && Array.isArray(value.files) ? value.files : []
		      })
		      .catch((error) => {
		        console.error('[file-mention] host list failed:', error)
		        return []
		      })
		    fetches.set(sessionId, { promise, at: Date.now() })
		    promise.then(
		      () => {},
		      () => {
		        const current = fetches.get(sessionId)
		        if (current !== undefined && current.promise === promise) fetches.delete(sessionId)
		      },
		    )
		    return promise
		  }
		
		  const source = {
		    trigger: '@',
		    name: 'file',
		    order: 4,
		    async candidates(session, { query, signal }) {
		      const files = await fetchFiles(session.sessionId)
		      if (signal !== undefined && signal.aborted) return []
		      return filterFiles(files, query, 50).map((f) => ({
		        name: f.slice(f.lastIndexOf('/') + 1),
		        description: f,
		        icon: '\ud83d\udcc4',
		      }))
		    },
		    onPick({ candidate }) {
		      return { text: '@' + candidate.description + ' ' }
		    },
		  }
		
		  ctx.effect(() => ctx.inputTriggers.registerSource(source), 'file-mention: @ source')
		}
		
		
		exports.name = name;
		exports.inject = inject;
		exports.apply = apply;
		return module.exports;
	}
});
