/* dsh-file-mention — generated by scripts/build.mjs; edit src/, then run `npm run build`. */
window.__ModuleLoader__.load({
	id: "dsh-file-mention",
	factory: (require) => {
		var module = { exports: {} };
		var exports = module.exports;
		Object.defineProperty(exports, Symbol.toStringTag, { value: "Module" });
		/**
		 * dsh-file-mention —— Client 半体
		 *
		 * 注册 '@' 输入触发源（与技能 / 菜单、@pluginId、@子代理 同一套 inputTriggers 机制）：
		 *   - 输入 @ 弹出 file 分组，按文件名/路径实时过滤
		 *   - 选中后插入 `@相对路径 ` 到输入框，模型看到路径后直接读取文件
		 *   - 列表经 Host 的 /file-mention/list HTTP 路由获取，客户端 30 秒缓存
		 *
		 * 构建时由 scripts/build.mjs 将 src/core.js 内联，并包装为
		 * `window.__ModuleLoader__.load({ id, factory })` 经典脚本格式。
		 */
		
		const name = 'dsh-file-mention'
		const inject = ['inputTriggers']
		
		function apply(ctx) {
		  const fetches = new Map()
		  const TTL = 30000
		
		  const fetchFiles = (sessionId) => {
		    const existing = fetches.get(sessionId)
		    if (existing !== undefined && Date.now() - existing.at < TTL) return existing.promise
		    if (existing !== undefined) fetches.delete(sessionId)
		    const promise = fetch('/file-mention/list', {
		      method: 'POST',
		      headers: { 'content-type': 'application/json' },
		      body: JSON.stringify({ sessionId }),
		    })
		      .then((response) => {
		        if (!response.ok) throw new Error(`HTTP ${response.status}`)
		        return response.json()
		      })
		      .then((value) => {
		        return value !== null && typeof value === 'object' && Array.isArray(value.files) ? value.files : []
		      })
		      .catch((error) => {
		        console.error('[file-mention] host list failed:', error)
		        return []
		      })
		    fetches.set(sessionId, { promise, at: Date.now() })
		    promise.then(
		      () => {},
		      () => {
		        const current = fetches.get(sessionId)
		        if (current !== undefined && current.promise === promise) fetches.delete(sessionId)
		      },
		    )
		    return promise
		  }
		
		  const source = {
		    trigger: '@',
		    name: 'file',
		    order: 4,
		    async candidates(session, { query, signal }) {
		      const files = await fetchFiles(session.sessionId)
		      if (signal !== undefined && signal.aborted) return []
		      return filterFiles(files, query, 50).map((f) => ({
		        name: f.slice(f.lastIndexOf('/') + 1),
		        description: f,
		        icon: '\ud83d\udcc4',
		      }))
		    },
		    onPick({ candidate }) {
		      return { text: '@' + candidate.description + ' ' }
		    },
		  }
		
		  ctx.effect(() => ctx.inputTriggers.registerSource(source), 'file-mention: @ source')
		}
		
		
		exports.name = name;
		exports.inject = inject;
		exports.apply = apply;
		return module.exports;
	}
});
