/* dsh-file-mention — generated by scripts/build.mjs; edit src/, then run `npm run build`. */
// ---- src/core.js (inlined) ----
/**
 * dsh-file-mention —— 规则匹配核心（纯函数，零依赖，可独立测试）
 *
 * 实现 gitignore/.aiinclude 风格的路径匹配子集：
 *   - `#` 注释、空行忽略
 *   - `!` 前缀表示否定（最后匹配者生效）
 *   - 末尾 `/` 表示仅目录
 *   - 开头 `/` 表示锚定于基准目录
 *   - 含 `/` 的模式按完整相对路径匹配；不含 `/` 的模式按 basename 任意层级匹配
 *   - `*` 匹配段内任意字符、`?` 匹配单字符、`**` 跨段匹配
 */

/** 段 → 正则片段：支持 *（段内任意）、?（单字符），其余按字面量转义。 */
function segmentToRegex(seg) {
  let out = ''
  for (const ch of seg) {
    if (ch === '*') out += '[^/]*'
    else if (ch === '?') out += '[^/]'
    else out += ch.replace(/[.+^${}()|[\]\\]/g, '\\$&')
  }
  return out
}

/** 编译规则行集合为可复用的匹配规则数组。 */
export function compileRules(lines) {
  const rules = []
  for (let raw of lines) {
    raw = raw.trim()
    if (raw === '' || raw.startsWith('#')) continue
    let negate = false
    if (raw.startsWith('!')) {
      negate = true
      raw = raw.slice(1).trim()
    }
    if (raw === '') continue
    const dirOnly = raw.endsWith('/')
    if (dirOnly) raw = raw.slice(0, -1)
    let anchored = raw.startsWith('/')
    if (anchored) raw = raw.slice(1)
    if (raw === '') continue
    const hasSlash = raw.includes('/')
    try {
      const src = raw
        .split('/')
        .map((seg) => (seg === '**' ? '(?:.*)' : segmentToRegex(seg)))
        .join('/')
      rules.push({ negate, dirOnly, anchored, hasSlash, re: new RegExp('^' + src + '$') })
    } catch {
      // 非法模式跳过
    }
  }
  return rules
}

/**
 * 返回 rel 命中的最后一条规则（gitignore 语义：最后匹配者生效）；
 * 未命中返回 undefined。
 */
export function lastMatchRule(rules, rel, isDir) {
  let win
  for (const r of rules) {
    if (r.dirOnly && !isDir) continue
    if (r.anchored || r.hasSlash) {
      if (r.re.test(rel)) win = r
    } else {
      const base = rel.slice(rel.lastIndexOf('/') + 1)
      if (r.re.test(base) || r.re.test(rel)) win = r
    }
  }
  return win
}

/** 判断相对路径 rel 是否命中规则集（最后匹配者生效，未命中为 false）。 */
export function matchRules(rules, rel, isDir) {
  const win = lastMatchRule(rules, rel, isDir)
  return win !== undefined ? !win.negate : false
}

/**
 * 按查询词过滤文件列表：匹配 basename 或完整路径（大小写不敏感）。
 * 客户端 @ 菜单的过滤逻辑，独立出来以便测试。
 */
export function filterFiles(files, query, limit = 50) {
  const q = String(query || '').trim().toLowerCase()
  let matches = files
  if (q !== '') {
    matches = files.filter((f) => {
      const base = f.slice(f.lastIndexOf('/') + 1).toLowerCase()
      return base.includes(q) || f.toLowerCase().includes(q)
    })
  }
  return matches.slice(0, limit)
}

// ---- src/host.js (inlined) ----
/**
 * dsh-file-mention —— Host 半体
 *
 * 通过 `webServer` 注册 `/file-mention/list` HTTP 路由：
 *   - 解析会话工作区（ctx.sessions）
 *   - 通过 git ls-files 列出跟踪文件（天然遵守 .gitignore，排除编译产物与未跟踪文件）
 *   - 读取工作区根目录 .aiinclude，把被忽略但 AI 需要的文件重新纳入
 *   - git 不可用/非仓库时回退为 .gitignore 解析 + 全量扫描
 *
 * 构建时由 scripts/build.mjs 将 src/core.js 内联进来，产物无任何外部依赖。
 */

const name = 'dsh-file-mention'
const inject = ['sessions', 'webServer']

/** 请求体大小上限（防御超大请求）。 */
const BODY_CAP_BYTES = 64 * 1024

/** 遍历时跳过的重型目录（.aiinclude 命中可覆盖）。 */
const SKIP = new Set([
  '.git', 'node_modules', '.gradle', '.idea', '.kotlin', '.cxx',
  '.externalNativeBuild', 'build', 'out', 'target', 'dist', 'release',
  'debug', '.dsh', '.agents', '.claude', '.codex', 'storages', 'sessions',
])
/** 文件总数上限。 */
const CAP = 3000
/** 遍历深度上限（doc 等深层目录可达 13 层）。 */
const MAX_DEPTH = 16

/** 路径统一为正斜杠形式。 */
function norm(p) {
  return typeof p === 'string' ? p.replace(/\\/g, '/') : ''
}

/** 安全读取文本文件；不存在或非文件返回 undefined。 */
async function readTextSafe(fs, path) {
  try {
    const target = await fs.resolve(path)
    const info = await fs.stat(target)
    if (info === undefined || info.type !== 'file') return undefined
    return await fs.readText(target)
  } catch {
    return undefined
  }
}

/**
 * 递归遍历收集命中的文件。
 *
 * - `includeFile(p)`：文件级命中判定（仅在未被继承时检查）。
 * - `inheritDir(p)`：目录级规则状态，返回 true（纳入并继承给子级）、
 *   false（显式排除，阻断继承）或 null（无规则，沿用父级继承状态）。
 *   这是 .aiinclude 目录规则（doc/）与否定规则（!doc/private/）的语义基础。
 */
async function walkFiles(fs, dirTarget, includeFile, inheritDir) {
  const out = []
  const walk = async (target, relPath, level, inherited) => {
    if (out.length >= CAP || level > MAX_DEPTH) return
    let entries
    try {
      entries = await fs.listDir(target)
    } catch {
      return
    }
    for (const entry of entries) {
      if (out.length >= CAP) return
      if (entry.type === 'directory') {
        const p = relPath === '' ? entry.name : relPath + '/' + entry.name
        let matched = inherited
        if (inheritDir !== null && inheritDir !== undefined) {
          const state = inheritDir(p)
          if (state !== null) matched = state
        }
        if (SKIP.has(entry.name) && !matched) continue
        await walk(entry.target, p, level + 1, matched)
      } else if (entry.type === 'file') {
        const p = relPath === '' ? entry.name : relPath + '/' + entry.name
        if (inherited || includeFile(p)) out.push(p)
      }
    }
  }
  await walk(dirTarget, '', 0, false)
  return out
}

/** 运行 git 命令并返回 stdout；失败或非零退出返回 undefined。 */
async function runGit(ctx, cwd, args) {
  const sp = ctx.get('subprocess')
  if (sp === undefined) return undefined
  try {
    const handle = sp.spawn({
      argv: ['git', ...args],
      cwd,
      stdio: {
        stdin: 'ignore',
        stdout: { maxBytes: 8 * 1024 * 1024 },
        stderr: { maxBytes: 65536 },
      },
      graceMs: 5000,
    })
    const outcome = await handle.done
    const text = handle.collected.stdout !== undefined ? handle.collected.stdout.readFrom(0).text : ''
    return outcome.exitCode === 0 ? text : undefined
  } catch (error) {
    console.error('[file-mention] git failed:', error)
    return undefined
  }
}

/** 读取 JSON 请求体；为空或解析失败返回 null。 */
async function readJsonBody(req) {
  const chunks = []
  let total = 0
  for await (const chunk of req) {
    const part = chunk
    total += part.length
    if (total > BODY_CAP_BYTES) {
      req.destroy()
      return null
    }
    chunks.push(part)
  }
  const text = Buffer.concat(chunks).toString('utf8')
  if (text === '') return null
  try {
    return JSON.parse(text)
  } catch {
    return null
  }
}

/** 写入 JSON 响应。 */
function json(res, value, status = 200) {
  res.writeHead(status, { 'content-type': 'application/json; charset=utf-8' })
  res.end(JSON.stringify(value))
}

function apply(ctx) {
  const handler = async (req, res) => {
    if (req.method !== 'POST') {
      res.writeHead(405)
      res.end()
      return
    }
    const contentType = req.headers['content-type'] ?? ''
    if (!contentType.toLowerCase().startsWith('application/json')) {
      res.writeHead(415)
      res.end()
      return
    }
    const body = await readJsonBody(req)
    const args = body !== null && typeof body === 'object' && !Array.isArray(body) ? body : null
    const sessionId =
      args !== null && typeof args === 'object' && typeof args.sessionId === 'string'
        ? args.sessionId
        : undefined
    const session = sessionId !== undefined ? ctx.sessions.get(sessionId) : undefined
    const cwd = session !== undefined && session.header !== undefined ? session.header.cwd : undefined
    if (typeof cwd !== 'string' || cwd.length === 0) {
      json(res, { files: [] })
      return
    }
    const fs = ctx.get('fs')
    if (fs === undefined) {
      json(res, { files: [] })
      return
    }
    try {
      const root = await fs.resolve(cwd)
      let files = []

      // 1) git 跟踪文件：天然遵守 .gitignore，排除编译产物与未跟踪文件
      const rootText = await runGit(ctx, cwd, ['rev-parse', '--show-toplevel'])
      const trackedText = rootText !== undefined ? await runGit(ctx, cwd, ['ls-files', '-c']) : undefined
      if (trackedText !== undefined) {
        const repoRoot = norm(rootText.trim())
        const cwdRelFromRepo =
          repoRoot !== '' && norm(cwd).startsWith(repoRoot + '/')
            ? norm(cwd).slice(repoRoot.length + 1)
            : ''
        files = trackedText
          .split(/\r?\n/)
          .map((l) => l.trim())
          .filter((l) => l !== '')
          .filter((p) => cwdRelFromRepo === '' || p.startsWith(cwdRelFromRepo + '/'))
          .map((p) => (cwdRelFromRepo === '' ? p : p.slice(cwdRelFromRepo.length + 1)))
      } else {
        // 回退：git 不可用/非仓库时，解析 .gitignore 后全量扫描
        const ignoreText = await readTextSafe(fs, cwd + '/.gitignore')
        const rules = compileRules(ignoreText !== undefined ? ignoreText.split(/\r?\n/) : [])
        files = await walkFiles(fs, root, (p) => !matchRules(rules, p, false), null)
      }

      // 2) .aiinclude：重新纳入被忽略/未跟踪但 AI 需要的文件
      const aiText = await readTextSafe(fs, cwd + '/.aiinclude')
      if (aiText !== undefined) {
        const aiRules = compileRules(aiText.split(/\r?\n/))
        const extras = await walkFiles(
          fs,
          root,
          (p) => matchRules(aiRules, p, false),
          (p) => {
            const win = lastMatchRule(aiRules, p, true)
            return win === undefined ? null : !win.negate
          },
        )
        const seen = new Set(files)
        for (const p of extras) {
          if (!seen.has(p)) {
            seen.add(p)
            files.push(p)
          }
        }
      }

      files = files.filter((p) => p !== '' && !p.endsWith('/')).slice(0, CAP).sort()
      json(res, { files })
    } catch (error) {
      console.error('[file-mention] list failed:', error)
      json(res, { files: [] })
    }
  }

  ctx.effect(
    () => ctx.webServer.register({ kind: 'exact', path: '/file-mention/list', handler }),
    'file-mention: /file-mention/list route',
  )
}


export { name, inject, apply };
