/* @hucj/dsh-file-mention — generated by scripts/build.mjs; edit src/, then run `npm run build`. */
// ---- src/core.js (inlined) ----
/**
 * dsh-file-mention —— 规则匹配核心（纯函数，零依赖，可独立测试）
 *
 * 实现 gitignore/.aiinclude 风格的路径匹配子集：
 *   - `#` 注释、空行忽略
 *   - `!` 前缀表示否定（最后匹配者生效）
 *   - 末尾 `/` 表示仅目录
 *   - 开头 `/` 表示锚定于基准目录
 *   - 含 `/` 的模式按完整相对路径匹配；不含 `/` 的模式按 basename 任意层级匹配
 *   - `*` 匹配段内任意字符、`?` 匹配单字符、`**` 跨段匹配
 */

/** 段 → 正则片段：支持 *（段内任意）、?（单字符），其余按字面量转义。 */
function segmentToRegex(seg) {
  let out = ''
  for (const ch of seg) {
    if (ch === '*') out += '[^/]*'
    else if (ch === '?') out += '[^/]'
    else out += ch.replace(/[.+^${}()|[\]\\]/g, '\\$&')
  }
  return out
}

/** 编译规则行集合为可复用的匹配规则数组。 */
function compileRules(lines) {
  const rules = []
  for (let raw of lines) {
    raw = raw.trim()
    if (raw === '' || raw.startsWith('#')) continue
    let negate = false
    if (raw.startsWith('!')) {
      negate = true
      raw = raw.slice(1).trim()
    }
    if (raw === '') continue
    const dirOnly = raw.endsWith('/')
    if (dirOnly) raw = raw.slice(0, -1)
    let anchored = raw.startsWith('/')
    if (anchored) raw = raw.slice(1)
    if (raw === '') continue
    const hasSlash = raw.includes('/')
    try {
      // 逐段编译：完整正则（匹配）+ 段列表（剪枝判定用）
      const segs = raw.split('/').map((seg) => {
        if (seg === '**') return { star: true, re: null }
        return { star: false, re: new RegExp('^' + segmentToRegex(seg) + '$') }
      })
      const src = segs.map((s) => (s.star ? '(?:.*)' : s.re.source.slice(1, -1))).join('/')
      rules.push({ negate, dirOnly, anchored, hasSlash, segs, re: new RegExp('^' + src + '$') })
    } catch {
      // 非法模式跳过
    }
  }
  return rules
}

/**
 * 剪枝判定：目录 relPath 是否**可能**通往某条规则的命中？
 * 为 false 时遍历可以安全跳过该目录（.aiinclude 目录规则场景可大幅减负）。
 *
 * - basename 非目录规则（如 `*.log`）：任意层级都可能命中 → 恒 true（不可剪枝）
 * - basename 目录规则（如 `doc/`）：仅目录名匹配时才有意义
 * - 锚定/含斜杠规则（如 `app/build/**`）：目录是某规则段序列的前缀时才可能
 */
function dirMayLeadToMatch(rules, relPath) {
  const pathSegs = relPath.split('/')
  for (const r of rules) {
    if (r.anchored || r.hasSlash) {
      // 段前缀匹配：pathSegs 必须逐段命中规则段前缀；'**' 通吃其后
      let ok = true
      for (let i = 0; i < pathSegs.length; i++) {
        const p = r.segs[i]
        if (p === undefined) {
          ok = false
          break
        }
        if (p.star) break
        if (!p.re.test(pathSegs[i])) {
          ok = false
          break
        }
      }
      if (ok) return true
    } else if (!r.dirOnly) {
      // basename 文件规则：任何目录都可能包含命中文件
      return true
    } else {
      // basename 目录规则：目录名命中即会继承
      const name = pathSegs[pathSegs.length - 1]
      if (r.re.test(name)) return true
    }
  }
  return false
}

/**
 * 返回 rel 命中的最后一条规则（gitignore 语义：最后匹配者生效）；
 * 未命中返回 undefined。
 */
function lastMatchRule(rules, rel, isDir) {
  let win
  for (const r of rules) {
    if (r.dirOnly && !isDir) continue
    if (r.anchored || r.hasSlash) {
      if (r.re.test(rel)) win = r
    } else {
      const base = rel.slice(rel.lastIndexOf('/') + 1)
      if (r.re.test(base) || r.re.test(rel)) win = r
    }
  }
  return win
}

/** 判断相对路径 rel 是否命中规则集（最后匹配者生效，未命中为 false）。 */
function matchRules(rules, rel, isDir) {
  const win = lastMatchRule(rules, rel, isDir)
  return win !== undefined ? !win.negate : false
}

/**
 * 解析 `git status --porcelain -z` 输出为变更文件路径列表。
 * 每条 `<XY> <path>\0`；重命名/复制（R/C）占两个字段，取新路径。
 * 路径含空格等特殊字符时依然精确（-z 不做引号转义）。
 */
function parseStatusZ(text) {
  const dirty = []
  const parts = text.split('\0')
  for (let i = 0; i < parts.length; i++) {
    const entry = parts[i]
    if (entry === '') continue
    const code = entry[0]
    if ((code === 'R' || code === 'C') && i + 1 < parts.length) {
      i += 1
      dirty.push(parts[i])
    } else {
      const path = entry.slice(3)
      if (path !== '') dirty.push(path)
    }
  }
  return dirty
}

/**
 * 按查询词过滤文件列表：匹配 basename 或完整路径（大小写不敏感）。
 * 客户端 @ 菜单的过滤逻辑，独立出来以便测试。
 *
 * 命中排序（score 升序 + rank 升序 + 组内字母序）：
 *   score 0. 精确匹配（完整路径或 basename 与查询词完全相等）
 *   score 1. 前缀匹配（完整路径或 basename 以查询词开头）
 *   score 2. 子串匹配（其余命中项）
 *   rank 0.  git 未提交变更（dirty 集合内）
 *   rank 1.  非隐藏目录（首段不以 . 开头）
 *   rank 2.  隐藏目录
 * 空查询时 score 恒为 0，退化为纯 rank + 字母序（与历史行为一致）。
 */
function filterFiles(files, query, limit = 100, dirty) {
  const q = String(query || '').trim().toLowerCase()
  const dirtySet = dirty instanceof Set ? dirty : undefined
  const rank = (f) => {
    if (dirtySet !== undefined && dirtySet.has(f)) return 0
    if (f.split('/')[0].startsWith('.')) return 2
    return 1
  }
  const score = (f) => {
    if (q === '') return 0
    const lower = f.toLowerCase()
    const base = f.slice(f.lastIndexOf('/') + 1).toLowerCase()
    if (lower === q || base === q) return 0
    if (base.startsWith(q) || lower.startsWith(q)) return 1
    return 2
  }
  let matches = files
  if (q !== '') {
    matches = files.filter((f) => {
      const base = f.slice(f.lastIndexOf('/') + 1).toLowerCase()
      return base.includes(q) || f.toLowerCase().includes(q)
    })
  }
  // 恒排序：空查询退化为 rank + 字母序（与历史行为一致），有查询词时 score 优先
  matches = [...matches].sort(
    (a, b) => score(a) - score(b) || rank(a) - rank(b) || (a < b ? -1 : a > b ? 1 : 0),
  )
  return matches.slice(0, limit)
}

/**
 * 将嵌套目录 `.aiinclude` 的规则行展平为「根相对」规则行，以便与根规则
 * 合并成一个规则集（last-match-wins 天然实现层级覆盖：后读入的嵌套规则优先）。
 *
 * 语义对齐 gitignore：目录 D 下的规则相对 D 生效——
 *   - 斜杠模式（`/x`、`x/y`、`x/`）：直接加 D 前缀；
 *   - basename 文件模式（`x`）：展开为 `D/x`（直接子级）与 `D/**` 跨段形式（任意深度）；
 *   - basename 目录模式（`x/`）：展开为 `D/x/` 与 `D/**` 跨段形式；
 *   - `**` 前缀模式（如 `**` + `/x`）：额外补 `D/x`（gitignore 语义：匹配 D 本身及其下任意深度）；
 *   - 取反 `!` 前缀保留，按行序参与 last-match-wins。
 *
 * @param {string} dir 嵌套文件所在目录（根相对，无首尾斜杠，如 `doc/sub`）
 * @param {string[]} lines 该 .aiinclude 的原始行
 * @returns {string[]} 展平后的规则行
 */
function flattenNestedRules(dir, lines) {
  const out = []
  for (let raw of lines) {
    raw = raw.trim()
    if (raw === '' || raw.startsWith('#')) continue
    let negate = ''
    if (raw.startsWith('!')) {
      negate = '!'
      raw = raw.slice(1).trim()
    }
    if (raw === '') continue
    const dirOnly = raw.endsWith('/')
    if (dirOnly) raw = raw.slice(0, -1)
    const anchored = raw.startsWith('/')
    if (anchored) raw = raw.slice(1)
    if (raw === '') continue
    const base = dir + '/' + raw
    if (anchored || raw.includes('/')) {
      out.push(negate + base + (dirOnly ? '/' : ''))
      if (raw.startsWith('**/')) {
        out.push(negate + dir + '/' + raw.slice(3) + (dirOnly ? '/' : ''))
      }
    } else if (dirOnly) {
      out.push(negate + base + '/')
      out.push(negate + dir + '/**/' + raw + '/')
    } else {
      out.push(negate + base)
      out.push(negate + dir + '/**/' + raw)
    }
  }
  return out
}

// ---- src/host.js (inlined) ----
/**
 * dsh-file-mention —— Host 半体
 *
 * 通过 `webServer` 注册 `/file-mention/list` HTTP 路由：
 *   - 解析会话工作区（ctx.sessions）
 *   - 通过 git ls-files 列出跟踪文件 + 未跟踪非忽略文件（两者都天然遵守
 *     .gitignore，排除编译产物；新建文件无需 git add 即可 @ 引用）
 *   - 读取工作区根目录 .aiinclude，把被忽略但 AI 需要的文件重新纳入
 *   - git 不可用/非仓库时回退为 .gitignore 解析 + 全量扫描
 *
 * 构建时由 scripts/build.mjs 将 src/core.js 内联进来，产物无任何外部依赖。
 */

const name = '@hucj/dsh-file-mention'
const inject = ['sessions', 'webServer']

/** 请求体大小上限（防御超大请求）。 */
const BODY_CAP_BYTES = 64 * 1024

/** 遍历时跳过的重型目录（.aiinclude 命中可覆盖）。 */
const SKIP = new Set([
  '.git', 'node_modules', '.gradle', '.idea', '.kotlin', '.cxx',
  '.externalNativeBuild', 'build', 'out', 'target', 'dist', 'release',
  'debug', '.dsh', '.agents', '.claude', '.codex', 'storages', 'sessions',
])
/** 文件总数上限（防超大仓库：列表体积、传输、客户端每次按键排序成本）。 */
const CAP = 10000
/** 遍历深度上限（真实项目普遍 ≤20 层，32 留足余量）。 */
const MAX_DEPTH = 32

/** git 结果缓存 TTL：仓库根几乎不变；跟踪列表变化慢；status 变化最快。 */
const GIT_ROOT_TTL = 60_000
const GIT_TRACKED_TTL = 15_000
const GIT_DIRTY_TTL = 5_000
const gitRootCache = new Map() // cwd -> { root, cwdRel, at }
const gitTrackedCache = new Map() // cwd -> { files, at }
const gitDirtyCache = new Map() // cwd -> { dirty, at }
const gitUntrackedCache = new Map() // cwd -> { files, at }（未跟踪非忽略文件，与 dirty 同 TTL）
const extrasCache = new Map() // cwd -> { extras, at }（.aiinclude 收集结果，与 tracked 同 TTL）

/** 读取 TTL 缓存条目；未过期返回条目，过期或缺失返回 null。 */
function cacheGet(map, key, ttl, now) {
  const entry = map.get(key)
  if (entry === undefined || now - entry.at >= ttl) return null
  return entry
}

/** 会话 header cwd 的持久化回退缓存：sessionId -> { cwd, at }。 */
const sessionCwdCache = new Map()
const SESSION_CWD_TTL = 60_000

/**
 * 从持久化层解析会话的 cwd（ctx.sessions 内存注册表缺失时使用，如历史对话）。
 * 返回 undefined 表示解析失败；结果按 sessionId 缓存 60s。
 */
async function resolveCwdFromPersistence(ctx, sessionId) {
  if (typeof sessionId !== 'string' || sessionId.length === 0) return undefined
  const memo = sessionCwdCache.get(sessionId)
  if (memo !== undefined && Date.now() - memo.at < SESSION_CWD_TTL) return memo.cwd
  const persistence = ctx.get('sessionPersistence')
  if (persistence === undefined) return undefined
  let cwd
  try {
    const info = await persistence.inspect(sessionId)
    // SessionInspection 结构取 header 字段（meta/header/sessionHeader 均防御）
    const meta =
      info !== null && typeof info === 'object'
        ? info.meta ?? info.header ?? info.sessionHeader ?? info.session?.header
        : undefined
    cwd = meta !== null && typeof meta === 'object' && typeof meta.cwd === 'string' ? meta.cwd : undefined
  } catch {
    cwd = undefined
  }
  sessionCwdCache.set(sessionId, { cwd, at: Date.now() })
  return cwd
}

/** 路径统一为正斜杠形式。 */
function norm(p) {
  return typeof p === 'string' ? p.replace(/\\/g, '/') : ''
}

/** 安全读取文本文件；不存在或非文件返回 undefined。 */
async function readTextSafe(fs, path) {
  try {
    const target = await fs.resolve(path)
    const info = await fs.stat(target)
    if (info === undefined || info.type !== 'file') return undefined
    return await fs.readText(target)
  } catch {
    return undefined
  }
}

/**
 * 递归遍历收集命中的文件。
 *
 * - `includeFile(p)`：文件级命中判定（仅在未被继承时检查）。
 * - `inheritDir(p)`：目录级规则状态，返回 true（纳入并继承给子级）、
 *   false（显式排除，阻断继承）或 null（无规则，沿用父级继承状态）。
 *   这是 .aiinclude 目录规则（doc/）与否定规则（!doc/private/）的语义基础。
 * - `mayContain(p)`：可选剪枝判定；目录不可能通往任何命中时跳过递归，
 *   大幅降低 .aiinclude 目录规则场景的遍历开销。
 */
async function walkFiles(fs, dirTarget, includeFile, inheritDir, mayContain) {
  const out = []
  const walk = async (target, relPath, level, inherited) => {
    if (out.length >= CAP || level > MAX_DEPTH) return
    let entries
    try {
      entries = await fs.listDir(target)
    } catch {
      return
    }
    for (const entry of entries) {
      if (out.length >= CAP) return
      if (entry.type === 'directory') {
        const p = relPath === '' ? entry.name : relPath + '/' + entry.name
        let matched = inherited
        if (inheritDir !== null && inheritDir !== undefined) {
          const state = inheritDir(p)
          if (state !== null) matched = state
        }
        if (SKIP.has(entry.name) && !matched) continue
        if (!matched && mayContain !== undefined && mayContain !== null && !mayContain(p)) continue
        await walk(entry.target, p, level + 1, matched)
      } else if (entry.type === 'file') {
        const p = relPath === '' ? entry.name : relPath + '/' + entry.name
        if (inherited || includeFile(p)) out.push(p)
      }
    }
  }
  await walk(dirTarget, '', 0, false)
  return out
}

/** 运行 git 命令并返回 stdout；失败或非零退出返回 undefined。 */
async function runGit(ctx, cwd, args) {
  const sp = ctx.get('subprocess')
  if (sp === undefined) return undefined
  try {
    const handle = sp.spawn({
      argv: ['git', ...args],
      cwd,
      stdio: {
        stdin: 'ignore',
        stdout: { maxBytes: 8 * 1024 * 1024 },
        stderr: { maxBytes: 65536 },
      },
      graceMs: 5000,
    })
    const outcome = await handle.done
    const text = handle.collected.stdout !== undefined ? handle.collected.stdout.readFrom(0).text : ''
    return outcome.exitCode === 0 ? text : undefined
  } catch (error) {
    console.error('[file-mention] git failed:', error)
    return undefined
  }
}

/** 读取 JSON 请求体；为空或解析失败返回 null。 */
async function readJsonBody(req) {
  const chunks = []
  let total = 0
  for await (const chunk of req) {
    const part = chunk
    total += part.length
    if (total > BODY_CAP_BYTES) {
      req.destroy()
      return null
    }
    chunks.push(part)
  }
  const text = Buffer.concat(chunks).toString('utf8')
  if (text === '') return null
  try {
    return JSON.parse(text)
  } catch {
    return null
  }
}

/** 写入 JSON 响应。 */
function json(res, value, status = 200) {
  res.writeHead(status, { 'content-type': 'application/json; charset=utf-8' })
  res.end(JSON.stringify(value))
}

/** 嵌套 .aiinclude 规则合并结果的缓存 TTL（毫秒）。 */
const AI_MEMO_TTL = 60_000
/** 嵌套 .aiinclude 发现数量上限（防御性）。 */
const AI_NESTED_CAP = 50
/** 嵌套规则合并缓存：cwd → { at, rules }。 */
const aiMemo = new Map()

/**
 * 全量遍历（仅跳过 SKIP 目录）发现各子目录中的 `.aiinclude` 文件，
 * 返回其所在目录列表（根相对路径）。用于加载嵌套配置。
 */
async function discoverNestedAiinclude(fs, root) {
  const dirs = []
  const walk = async (target, relPath, level) => {
    if (dirs.length >= AI_NESTED_CAP || level >= MAX_DEPTH) return
    let entries
    try {
      entries = await fs.listDir(target)
    } catch {
      return
    }
    for (const entry of entries) {
      if (dirs.length >= AI_NESTED_CAP) return
      if (entry.type === 'directory') {
        if (SKIP.has(entry.name)) continue
        await walk(entry.target, relPath === '' ? entry.name : relPath + '/' + entry.name, level + 1)
      } else if (entry.type === 'file' && entry.name === '.aiinclude') {
        if (relPath !== '') dirs.push(relPath)
      }
    }
  }
  await walk(root, '', 0)
  return dirs
}

/**
 * 加载工作区的 .aiinclude 规则（根 + 嵌套，合并为单一规则集）。
 *
 * - 根 .aiinclude 不存在 → 返回 null（不启用 .aiinclude 逻辑，零开销）。
 * - 根存在 → 全量发现嵌套 .aiinclude（SKIP 目录内的不读），规则展平为根相对
 *   后按行序追加，last-match-wins 使嵌套规则覆盖根规则；`!` 否定同样参与，
 *   与遍历继承逻辑（inheritDir）自然协作。
 * - 结果按 cwd 内存缓存 AI_MEMO_TTL（60s），避免每次请求重复全量扫描。
 */
async function loadAiRules(fs, cwd, root) {
  const memo = aiMemo.get(cwd)
  if (memo !== undefined && Date.now() - memo.at < AI_MEMO_TTL) return memo.rules
  const rootText = await readTextSafe(fs, cwd + '/.aiinclude')
  const lines = []
  if (rootText !== undefined) {
    lines.push(...rootText.split(/\r?\n/))
    const nestedDirs = await discoverNestedAiinclude(fs, root)
    for (const dir of nestedDirs) {
      const text = await readTextSafe(fs, cwd + '/' + dir + '/.aiinclude')
      if (text !== undefined) lines.push(...flattenNestedRules(dir, text.split(/\r?\n/)))
    }
  }
  const rules = lines.length > 0 ? compileRules(lines) : null
  aiMemo.set(cwd, { at: Date.now(), rules })
  return rules
}

function apply(ctx) {
  const handler = async (req, res) => {
    if (req.method !== 'POST') {
      res.writeHead(405)
      res.end()
      return
    }
    const contentType = req.headers['content-type'] ?? ''
    if (!contentType.toLowerCase().startsWith('application/json')) {
      res.writeHead(415)
      res.end()
      return
    }
    const body = await readJsonBody(req)
    const args = body !== null && typeof body === 'object' && !Array.isArray(body) ? body : null
    const sessionId =
      args !== null && typeof args === 'object' && typeof args.sessionId === 'string'
        ? args.sessionId
        : undefined
    const session = sessionId !== undefined ? ctx.sessions.get(sessionId) : undefined
    let cwd = session !== undefined && session.header !== undefined ? session.header.cwd : undefined
    if (typeof cwd !== 'string' || cwd.length === 0) {
      // 内存注册表（ctx.sessions）只含活跃/已恢复会话；左侧历史对话不在其中时，
      // 回退到持久化层读取会话 header 拿 cwd（60s 缓存，避免每次请求读盘）。
      cwd = await resolveCwdFromPersistence(ctx, sessionId)
    }
    if (typeof cwd !== 'string' || cwd.length === 0) {
      json(res, { files: [] })
      return
    }
    const fs = ctx.get('fs')
    if (fs === undefined) {
      json(res, { files: [] })
      return
    }
    try {
      const root = await fs.resolve(cwd)
      let files = []
      let dirty = []

      // 1) git 跟踪文件：天然遵守 .gitignore，排除编译产物与未跟踪文件
      //    结果分层缓存（root 60s / tracked 15s / dirty 5s），TTL 内不重复跑 git 子进程；
      //    陈旧上限即 TTL，客户端侧 30s SWR 缓存比它更"旧"，因此整体一致性不受影响。
      const now = Date.now()
      const rootEntry = cacheGet(gitRootCache, cwd, GIT_ROOT_TTL, now)
      let repoRoot = ''
      let cwdRelFromRepo = ''
      if (rootEntry !== null) {
        repoRoot = rootEntry.root
        cwdRelFromRepo = rootEntry.cwdRel
      } else {
        const rootText = await runGit(ctx, cwd, ['rev-parse', '--show-toplevel'])
        if (rootText !== undefined) {
          repoRoot = norm(rootText.trim())
          cwdRelFromRepo =
            repoRoot !== '' && norm(cwd).startsWith(repoRoot + '/')
              ? norm(cwd).slice(repoRoot.length + 1)
              : ''
        }
        // 非仓库也缓存（root=''），60s 内不再重复探测；git init 后最多 60s 识别
        gitRootCache.set(cwd, { root: repoRoot, cwdRel: cwdRelFromRepo, at: now })
      }

      const trackedEntry = cacheGet(gitTrackedCache, cwd, GIT_TRACKED_TTL, now)
      if (trackedEntry !== null) {
        files = trackedEntry.files
      } else if (repoRoot !== '') {
        const trackedText = await runGit(ctx, cwd, ['ls-files', '-c'])
        if (trackedText !== undefined) {
          files = trackedText
            .split(/\r?\n/)
            .map((l) => l.trim())
            .filter((l) => l !== '')
            .filter((p) => cwdRelFromRepo === '' || p.startsWith(cwdRelFromRepo + '/'))
            .map((p) => (cwdRelFromRepo === '' ? p : p.slice(cwdRelFromRepo.length + 1)))
          gitTrackedCache.set(cwd, { files, at: Date.now() })
        }
      } else {
        // 回退：git 不可用/非仓库时，解析 .gitignore 后全量扫描（结果同样缓存 15s）
        const ignoreText = await readTextSafe(fs, cwd + '/.gitignore')
        const rules = compileRules(ignoreText !== undefined ? ignoreText.split(/\r?\n/) : [])
        files = await walkFiles(fs, root, (p) => !matchRules(rules, p, false), null)
        gitTrackedCache.set(cwd, { files, at: Date.now() })
      }

      // 1b) 未提交变更（staged + unstaged + 删除 + 未跟踪）：@ 默认排序优先展示
      const dirtyEntry = cacheGet(gitDirtyCache, cwd, GIT_DIRTY_TTL, now)
      if (dirtyEntry !== null) {
        dirty = dirtyEntry.dirty
      } else if (repoRoot !== '') {
        const statusText = await runGit(ctx, cwd, ['status', '--porcelain', '-z'])
        if (statusText !== undefined) {
          dirty = parseStatusZ(statusText)
            .filter((p) => cwdRelFromRepo === '' || p.startsWith(cwdRelFromRepo + '/'))
            .map((p) => (cwdRelFromRepo === '' ? p : p.slice(cwdRelFromRepo.length + 1)))
          gitDirtyCache.set(cwd, { dirty, at: Date.now() })
        }
      }

      // 1c) 未跟踪且未被忽略的文件（新建文件）：git status 会把整个未跟踪目录折叠成
      //     一条 `?? dir/`，再经下方末尾 '/' 过滤后彻底丢失，新文件永远进不了菜单；
      //     git ls-files -o --exclude-standard 输出单个文件路径，且天然遵守
      //     .gitignore（编译产物不进来）。与 dirty 同 TTL（新建/删除变化最快）。
      const untrackedEntry = cacheGet(gitUntrackedCache, cwd, GIT_DIRTY_TTL, now)
      let untracked = []
      if (untrackedEntry !== null) {
        untracked = untrackedEntry.files
      } else if (repoRoot !== '') {
        const untrackedText = await runGit(ctx, cwd, ['ls-files', '-o', '--exclude-standard'])
        if (untrackedText !== undefined) {
          untracked = untrackedText
            .split(/\r?\n/)
            .map((l) => l.trim())
            .filter((l) => l !== '')
            .filter((p) => cwdRelFromRepo === '' || p.startsWith(cwdRelFromRepo + '/'))
            .map((p) => (cwdRelFromRepo === '' ? p : p.slice(cwdRelFromRepo.length + 1)))
          gitUntrackedCache.set(cwd, { files: untracked, at: Date.now() })
        }
      }

      // 1d) 未跟踪文件并入主列表（新文件无需 git add 即可 @ 引用），并标记为变更
      //     优先——dirty 只参与客户端排序、不新增条目，所以两处都要合并。
      const seenAll = new Set(files)
      const dirtySet = new Set(dirty)
      for (const p of untracked) {
        if (p === '' || p.endsWith('/')) continue
        if (!seenAll.has(p)) {
          seenAll.add(p)
          files.push(p)
        }
        if (!dirtySet.has(p)) {
          dirtySet.add(p)
          dirty.push(p)
        }
      }

      // 2) .aiinclude：重新纳入被忽略/未跟踪但 AI 需要的文件（支持子目录嵌套配置）
      //    extras 收集结果同样缓存 15s（与 tracked 同 TTL）——该 walk 遍历 doc/ 级
      //    子树（实测 ~370ms/次），是热请求的大头；aiRules 为 null（无配置）时
      //    整个逻辑跳过，因此缓存不会在配置被删除后残留。
      const aiRules = await loadAiRules(fs, cwd, root)
      if (aiRules !== null) {
        let extras
        const extrasEntry = cacheGet(extrasCache, cwd, GIT_TRACKED_TTL, now)
        if (extrasEntry !== null) {
          extras = extrasEntry.extras
        } else {
          extras = await walkFiles(
            fs,
            root,
            (p) => matchRules(aiRules, p, false),
            (p) => {
              const win = lastMatchRule(aiRules, p, true)
              return win === undefined ? null : !win.negate
            },
            (p) => dirMayLeadToMatch(aiRules, p),
          )
          extrasCache.set(cwd, { extras, at: Date.now() })
        }
        const seen = new Set(files)
        for (const p of extras) {
          if (!seen.has(p)) {
            seen.add(p)
            files.push(p)
          }
        }
      }

      files = files.filter((p) => p !== '' && !p.endsWith('/')).slice(0, CAP).sort()
      // cwd 用于客户端按工作区共享缓存（同工作区多会话只扫描一次）
      json(res, { files, dirty, cwd })
    } catch (error) {
      console.error('[file-mention] list failed:', error)
      json(res, { files: [], dirty: [] })
    }
  }

  ctx.effect(
    () => ctx.webServer.register({ kind: 'exact', path: '/file-mention/list', handler }),
    'file-mention: /file-mention/list route',
  )
}


export { name, inject, apply };
