/**
 * 构建脚本：把 src/* 内联打包为 lib/ 安装产物（零外部依赖）。
 *
 *   src/core.js   —— 纯函数匹配器（编译后内联进两个产物）
 *   src/host.js   —— Host 半体 → lib/index.js（ESM，具名导出）
 *   src/client.js —— Client 半体 → lib/client.js（__ModuleLoader__ 经典脚本包装）
 *
 * 用法：node scripts/build.mjs
 */
import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { execFileSync } from 'node:child_process'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = dirname(dirname(fileURLToPath(import.meta.url)))
const read = (p) => readFile(join(root, p), 'utf8')

const stripExportLine = (src) => src.replace(/^export\s*\{[^}]*\};?\s*$/gm, '')
const stripCoreImport = (src) => src.replace(/^import\s*\{[^}]*\}\s*from\s*'\.\/core\.js';?\s*$/gm, '')

const core = stripExportLine(await read('src/core.js'))
const host = stripCoreImport(await read('src/host.js')).replace(/^export\s*\{[^}]*\};?\s*$/gm, '')
const client = stripCoreImport(await read('src/client.js')).replace(/^export\s*\{[^}]*\};?\s*$/gm, '')

const banner = '/* dsh-file-mention — generated by scripts/build.mjs; edit src/, then run `npm run build`. */\n'

// ---- Host 产物：ESM 具名导出 ----
const indexJs =
  banner +
  '// ---- src/core.js (inlined) ----\n' +
  core +
  '\n// ---- src/host.js (inlined) ----\n' +
  host +
  '\nexport { name, inject, apply };\n'

// ---- Client 产物：经典脚本 + CJS factory（与 DSH 打包约定一致）----
const clientJs =
  banner +
  'window.__ModuleLoader__.load({\n' +
  '\tid: "dsh-file-mention",\n' +
  '\tfactory: (require) => {\n' +
  '\t\tvar module = { exports: {} };\n' +
  '\t\tvar exports = module.exports;\n' +
  '\t\tObject.defineProperty(exports, Symbol.toStringTag, { value: "Module" });\n' +
  client
    .split('\n')
    .map((line) => '\t\t' + line)
    .join('\n') +
  '\n\t\texports.name = name;\n' +
  '\t\texports.inject = inject;\n' +
  '\t\texports.apply = apply;\n' +
  '\t\treturn module.exports;\n' +
  '\t}\n' +
  '});\n'

await mkdir(join(root, 'lib'), { recursive: true })
await writeFile(join(root, 'lib/index.js'), indexJs, 'utf8')
await writeFile(join(root, 'lib/client.js'), clientJs, 'utf8')

// 语法校验
for (const file of ['lib/index.js', 'lib/client.js']) {
  execFileSync(process.execPath, ['--check', join(root, file)], { stdio: 'inherit' })
  console.log(`✓ ${file} syntax OK`)
}
console.log('✓ build done: lib/index.js, lib/client.js')
